export const bankNames = [
 'Access Bank',
 'Citibank',
 'Diamond Bank',
 'Ecobank Nigeria',
 'Fidelity Bank',
 'First Bank of Nigeria',
 'First City Monument Bank',
 'Guaranty Trust Bank',
 'Heritage Bank',
 'Keystone Bank',
 'Polaris Bank',
 'Stanbic IBTC Bank',
 'Standard Chartered Bank',
 'Sterling Bank',
 'SunTrust Bank',
 'Union Bank of Nigeria',
 'United Bank for Africa (UBA)',
 'Unity Bank',
 'Wema Bank',
 'Zenith Bank',
];
